cam0:
  camera_model: pinhole
  intrinsics: [918.1359807, 917.4572847, 644.8085022, 363.1237915]
  distortion_model: rational_polynomial
  distortion_coeffs: [-0.07797829157, -0.275521566, -0.0009005399526, 0.0002086778127, 0.3551218176, -0.2277495576, 0.1519481704, 0.05761514408]
  resolution: [1280, 720]
  image_topic: /left/camera/color/image_raw
  # image_transport: raw
  tag_topic: /cam_sync/cam_0/detector/tags
  tag_detector: umich
  rig_body: rig
cam1:
  camera_model: pinhole
  intrinsics: [1388.89, 1388.70, 969.69, 538.37841]
  distortion_model: plumb_bob
  distortion_coeffs: [0, 0, 0, 0, 0]
  resolution: [1920, 1080]
  image_topic: /back/camera/color/image_raw
  # image_transport: raw
  tag_topic: /cam_sync/cam_1/detector/tags
  tag_detector: umich
  rig_body: rig
cam2:
  camera_model: pinhole
  intrinsics: [1390.3, 1389.25, 968.4056, 536.008]
  distortion_model: plumb_bob
  distortion_coeffs: [0, 0, 0, 0, 0]
  resolution: [1920, 1080]
  image_topic: /right/camera/color/image_raw
  #for infra1 detecting
  # image_topic: /right/camera/infra1/image_rect_raw
  # image_transport: raw
  tag_topic: /cam_sync/cam_2/detector/tags
  tag_detector: umich
  rig_body: rig
