/**:
  ros__parameters:
    enable_depth: false
    enable_infra1: false
    enable_infra2: false

    enable_color: true

    rgb_camera.color_format: "RGB8"
    
    rgb_camera.color_profile: 1920x1080x30

    rgb_camera.enable_auto_exposure: false
    rgb_camera.exposure: 83
    rgb_camera.gain: 128
    rgb_camera.brightness: 0
    rgb_camera.contrast: 50
    rgb_camera.gamma: 300
    rgb_camera.hue: 0
    rgb_camera.saturation: 56
    rgb_camera.sharpness: 50
    rgb_camera.enable_auto_white_balance: false
    rgb_camera.white_balance: 2800.0



