amnesia: true # the goat?
tagslam_parameters:
  # optimizer mode: full (full optimization, no iSAM2 used)
  #                 slow (use iSAM2, but test for error and use full if error is large)
  #                 fast (iSAM2 only, no test for error)
  # default: slow
  optimizer_mode: slow
  # minimum angle [in degrees] between optical axis and tag surface
  minimum_viewing_angle: 5.0
  # minimum tag area in pixels^2. Any tags smaller than that are ignored
  minimum_tag_area: 1000
  # number of incremental updates before running
  # a full graph optimization (default: 50) # NOTE: commented out below
  # max_num_incremental_opt: 50000
  # estimated error of tag corner detector
  pixel_noise: 1.0
  # maximum allowed subgraph error. If error is above that,
  # the frame is thrown away, the measurement ignored.
  max_subgraph_error: 1000.0
  # Noise with which the subgraph absolute priors will be
  # pinned down. This parameter usually does not need to be touched.
  # subgraph_abs_prior_position_noise: 0.1
  # subgraph_abs_prior_rotation_noise: 0.1
  # if the time stamps (header.stamp) of your data messages are not
  # identical (hardware synced), set this option to true, and
  # tagslam tries to line them up as well as possible. Expect larger errors
  # because the data is not truly synchronous.
  use_approximate_sync: true
  sync_queue_size: 10
body_defaults:
  position_noise: 0.05
  rotation_noise: 0.01
# default_body: no_body   # don't specify  default body: ignore all tags not listed
default_body: map
bodies:
  - map:
      is_static: true
      default_tag_size: 0.145
      pose:
        position:
          x: 0
          y: 0
          z: 0
        rotation:
          x: 0
          y: 0
          z: 0
        position_noise:
          x: 0.0001
          y: 0.0001
          z: 0.0001
        rotation_noise:
          x: 1.0e-05
          y: 1.0e-05
          z: 1.0e-05
      type: simple
      tags:
      - id: 0
        pose: 
          position:
            x: -3.750
            y: -0.321
            z: 0.288
          rotation:
            x: -1.209199576
            y: 1.209199576
            z: -1.209199576
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 1
        pose: 
          position:
            x: -3.580
            y: -1.334
            z: 0.288
          rotation:
            x: -1.209199576
            y: -1.209199576
            z: 1.209199576
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 2
        pose: 
          position:
            x: -1.001
            y: -2.800
            z: 0.288
          rotation:
            x: -1.209199576
            y: 1.209199576
            z: -1.209199576
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 3
        pose: 
          position:
            x: 1.001
            y: -2.800
            z: 0.288
          rotation:
            x: -1.209199576
            y: -1.209199576
            z: 1.209199576
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 4
        pose: 
          position:
            x: 3.580
            y: -1.334
            z: 0.288
          rotation:
            x: -1.209199576
            y: 1.209199576
            z: -1.209199576
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 5
        pose: 
          position:
            x: 3.750
            y: -0.321
            z: 0.288
          rotation:
            x: -1.209199576
            y: -1.209199576
            z: 1.209199576
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 6
        pose: 
          position:
            x: 5.000
            y: 3.999
            z: 0.288
          rotation:
            x: -1.570796327
            y: 0.0
            z: 0.0
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 7
        pose: 
          position:
            x: 0.000
            y: -2.299
            z: 0.288
          rotation:
            x: 0.0
            y: -2.221441469
            z: 2.221441469
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 8
        pose: 
          position:
            x: 0.000
            y: 2.9839
            z: 0.288
          rotation:
            x: -1.570796327
            y: 0.0
            z: 0.0
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
      - id: 9
        pose: 
          position:
            x: -5.000
            y: 3.999
            z: 0.288
          rotation:
            x: -1.570796327
            y: 0.0
            z: 0.0
          position_noise:
            x: 0.002
            y: 0.002
            z: 0.002
          rotation_noise:
            x: 0.0174533
            y: 0.0174533
            z: 0.0174533
  - rig:
      type: simple
      is_static: false
      publish_tf: false
      odom_frame_id: "rig"
      odom_topic: "/uart/odometry" #actuly works now but its bad
      T_body_odom:
        position:
          x:  0
          y:  0
          z:  0
        rotation:
          x:  0
          y:  0
          z:  0
