v4l2_camera:
  ros__parameters:
    framerate: 15
    pixel_format: YUYV
    video_device: "/dev/v4l/by-id/usb-Arducam_Arducam_B0495__USB3_2.3MP__Arducam_202500915_0001-video-index0"
    image_size: [1920, 1200]

    auto_exposure: 1
    brightness: 8
    contrast: 10
    saturation: 8
    white_balance_automatic: false
    white_balance_temperature: 2500
  
    gain: 168
    exposure_time_absolute: 102
    camera_info_url: "file:///home/ubuntu/realsense_ws/cal/cam_info_front_1920.yaml"

